services:
 canopy-opensearch:
   image: public.ecr.aws/opensearchproject/opensearch:2.11.1
   environment:
     - discovery.type=single-node
     - bootstrap.memory_lock=true
     - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
     - "DISABLE_SECURITY_PLUGIN=true"
     - "DISABLE_INSTALL_DEMO_CONFIG=true"
   ports:
     - "9200:9200"
     - "9600:9600"
   ulimits:
     memlock:
       soft: -1
       hard: -1
   volumes:
     - canopy-opensearch-data:/usr/share/opensearch/data

 canopy-opensearch-dashboards:
   image: public.ecr.aws/opensearchproject/opensearch-dashboards:2.11.1
   ports:
     - "5601:5601"
   environment:
     - 'OPENSEARCH_HOSTS=["http://canopy-opensearch:9200"]'
     - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
   depends_on:
     - canopy-opensearch

volumes:
 canopy-opensearch-data:
